# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         346 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.87103970388845959E+012],]
input.xhen=[[  0.29191326996051410E+006],]
input.tmp_hetrates=[[  0.28344849183165465E-004],]
input.work1=[[  0.56443372811972172E+014],]
input.work2=[[  0.38760556209441924E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.30077018976502559E-004],]
