# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         341 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.12760634604156931E+013],]
input.xhen=[[  0.29938045965164859E+006],]
input.tmp_hetrates=[[  0.35556628295679050E-004],]
input.work1=[[  0.82688912234936891E+014],]
input.work2=[[  0.38719081776375992E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.37731771691452433E-004],]
