# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         350 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.10280264982207500E+013],]
input.xhen=[[  0.29568340498611523E+006],]
input.tmp_hetrates=[[  0.30911128008984844E-004],]
input.work1=[[  0.66616117084704602E+014],]
input.work2=[[  0.38739474022304867E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.32834706063132255E-004],]
