# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         340 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.12994720424702769E+013],]
input.xhen=[[  0.30216702366970247E+006],]
input.tmp_hetrates=[[  0.32593682353012883E-004],]
input.work1=[[  0.84205788352073969E+014],]
input.work2=[[  0.38703891337994732E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.34798875103656187E-004],]
