# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.satf=[[0.1600000000E-001],]
input.rain=[[0.1111150972E+013],]
input.xhen=[[0.2996217203E+006],]
input.tmp_hetrates=[[0.3332681352E-004],]
input.work1=[[0.7200258296E+014],]
input.work2=[[0.3871776054E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[0.3534958569E-004],]
