# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         347 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.86826976318605212E+012],]
input.xhen=[[  0.29345611882399657E+006],]
input.tmp_hetrates=[[  0.38137429630925933E-004],]
input.work1=[[  0.56263880654456164E+014],]
input.work2=[[  0.38751893261241895E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.39871568898471380E-004],]
