# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         343 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.11346715041122395E+013],]
input.xhen=[[  0.29494039557230350E+006],]
input.tmp_hetrates=[[  0.33386126760689573E-004],]
input.work1=[[  0.73526713466473125E+014],]
input.work2=[[  0.38743605693633488E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.35415366591395490E-004],]
