# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         344 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.10689155412920929E+013],]
input.xhen=[[  0.29251167747970298E+006],]
input.tmp_hetrates=[[  0.32546188873923279E-004],]
input.work1=[[  0.69265727075727617E+014],]
input.work2=[[  0.38757190325458990E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.34501112143199668E-004],]
