# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         349 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.10323043503402238E+013],]
input.xhen=[[  0.29431233501811733E+006],]
input.tmp_hetrates=[[  0.41178964330330261E-004],]
input.work1=[[  0.66893321902046484E+014],]
input.work2=[[  0.38747106981395050E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.43102217118664846E-004],]
