# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         345 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.satf=[[  0.16000000000000000E-001],]
input.rain=[[  0.10443852495855887E+013],]
input.xhen=[[  0.29146358431686967E+006],]
input.tmp_hetrates=[[  0.30503353478533301E-004],]
input.work1=[[  0.67676164173146133E+014],]
input.work2=[[  0.38763090501830060E-019],]
# Output data is stored here.
output = Object()
output.het_rates=[[  0.32429138683102807E-004],]
