# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.temp = [273.15, ]

# Output data is stored here.
output = Object()
output.air_dynamic_viscosity = [1.720760998e-05, ]
