# Data at [lat=   38.0068938875434      , lon=   196.003127824631      , k=          54 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.landfrac=[[  0.00000000000000000E+000],]
input.icefrac=[[  0.00000000000000000E+000],]
input.ocnfrac=[[  0.10000000000000000E+001],]
input.obklen=[[ -0.67625471546900570E+002],]
input.ustar=[[  0.34331692765594723E+000],]
input.ram1_in=[[  0.00000000000000000E+000],]
input.tair=[[  0.28179557952154045E+003],]
input.pmid=[[  0.10028049601711976E+006],]
input.pdel=[[  0.30200967693903658E+003],]
input.fv_in=[[  0.00000000000000000E+000],]
input.pcols=[[         4],]
input.rair=[[  0.28704231136504870E+003],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.ram1_out=[[  0.82373699671484005E+002],]
output.fv_out=[[  0.34331692765594723E+000],]
