# Data at [lat=   38.0068938875434      , lon=   196.003127824631      , k=          54 , time step=        1408 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.landfrac=[[  0.00000000000000000E+000],]
input.icefrac=[[  0.00000000000000000E+000],]
input.ocnfrac=[[  0.10000000000000000E+001],]
input.obklen=[[ -0.97645910872827869E+002],]
input.ustar=[[  0.38607414302973503E+000],]
input.ram1_in=[[  0.00000000000000000E+000],]
input.tair=[[  0.28257227289343774E+003],]
input.pmid=[[  0.10000357224796458E+006],]
input.pdel=[[  0.30117567968751246E+003],]
input.fv_in=[[  0.00000000000000000E+000],]
input.pcols=[[         4],]
input.rair=[[  0.28704231136504870E+003],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.ram1_out=[[  0.73877683313182857E+002],]
output.fv_out=[[  0.38607414302973503E+000],]
