# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.dynamic_viscosity = [2e-06, ]
input.particle_density = [12, ]
input.particle_radius = [1e-07, ]
input.particle_sig = [1, ]
input.slip_correction = [1.01, ]

# Output data is stored here.
output = Object()
output.gravit_settling_velocity = [1.32056288e-07, ]
