# Data at [lat=  -4.98879105856447      , lon=   28.0026147968828      , k=          52 , time step=        1397 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.fraction_landuse=[[  0.20918898065265040E-002,  0.10112323792561469E+000,  0.19104123086831826E+000,  0.56703179010502225E+000,  0.00000000000000000E+000,  0.42019237748858657E-001,  0.85693761223933115E-001,  0.66234294754917442E-002,  0.00000000000000000E+000,  0.00000000000000000E+000,  0.43754228462347953E-002,],]
input.n_land_type=[[        11],]
input.moment=[[         3],]
input.ncol=[[         4],]
input.pcols=[[         4],]
input.lchnk=[[       154],]
input.radius_max=[[  0.50000000000000002E-004],]
input.tair=[[  0.29277104074805010E+003],]
input.pmid=[[  0.92207156070349418E+005],]
input.radius_part=[[  0.44560232415501760E-007],]
input.density_part=[[  0.10681299950593370E+004],]
input.sig_part=[[  0.16000000000000001E+001],]
input.fricvel=[[  0.18893729762372757E+000],]
input.ram1=[[  0.94996675358271361E+002],]
input.vlc_grv=[[  0.20165226832706744E-005],]
# Output data is stored here.
output = Object()
output.vlc_trb=[[  0.16014634609407598E-002],]
output.vlc_dry=[[  0.16034799836240306E-002],]
