# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.moment = [1, ]
input.radius_max = [1e-05, ]
input.radius_part = [1e-06, ]
input.sig_part = [1, ]

# Output data is stored here.
output = Object()
output.radius_for_moment = [1e-06, ]
