# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.pres = [100000, ]
input.radius = [1e-06, ]
input.temp = [273.15, ]
input.vsc_dyn_atm = [1e-06, ]
input.vsc_knm_atm = [1e-07, ]

# Output data is stored here.
output = Object()
output.schmidt_number = [497.6278998, ]
