# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.dyn_visc = [1e-06, ]
input.particle_radius = [1e-06, ]
input.pres = [100000, ]
input.temp = [273.15, ]

# Output data is stored here.
output = Object()
output.slip_correction_factor = [1.004411322, ]
