# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ]
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.var_in=[[0.0000000000E+000,0.1500000000E+002,0.3000000000E+002,0.4500000000E+002,0.6000000000E+002,0.7000000000E+002,0.7500000000E+002,0.8000000000E+002,0.8250000000E+002,0.8500000000E+002,0.8700000000E+002,0.8900000000E+002,0.9000000000E+002,0.9050000000E+002,0.9100000000E+002,0.9150000000E+002,0.9200000000E+002,0.9250000000E+002,0.9300000000E+002,0.9350000000E+002,0.9400000000E+002,0.9500000000E+002,0.9600000000E+002,0.9700000000E+002,],]
input.var_len=[[        24],]
input.var_min=[[0.7739422321E+002],]
# Output data is stored here.
output = Object()
output.idx_out=[[         7],]
