# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          53 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.imode=[[         1],]
input.ncol=[[         4],]
input.isprx=[[         T],]
input.dgn_awet=[[ 0.1522452427E-06, 0.4627511718E-07, 0.1886138608E-05, 0.9911179496E-07,],]
input.dgnum_amode=[[ 0.1100000000E-06, 0.2600000000E-07, 0.2000000000E-05, 0.5000000058E-07,],]
# Output data is stored here.
output = Object()
output.scavcoefnum=[[ 0.6254861968E-03],]
output.scavcoefvol=[[ 0.1407235720E-02],]
