# Data at [lat=  0.000000000000000E+000 , lon=  0.000000000000000E+000 , k=           0 , time step=           0 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.dg0=[[ 0.2306867200E-05],]
input.sigmag=[[ 0.1800000000E+01],]
input.rhoaero=[[ 0.1770000000E+01],]
input.temp=[[ 0.2731600000E+03],]
input.press=[[ 0.7500000000E+06],]
input.lunerr=[[         6],]
# Output data is stored here.
output = Object()
output.scavratenum=[[ 0.3457011471E-02],]
output.scavratevol=[[ 0.1061631731E-02],]
