# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          55 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.cld=[[  0.63094534408394366E-002],]
input.maxsubarea=[[         2],]
# Output data is stored here.
output = Object()
output.nsubarea=[[         2],]
output.ncldy_subarea=[[         1],]
output.jclea=[[         1],]
output.jcldy=[[         2],]
output.iscldy_subarea=[[         0,         1,],]
output.afracsub=[[  0.99369054655916056E+000,  0.63094534408394366E-002,],]
output.fclea=[[  0.99369054655916056E+000],]
output.fcldy=[[  0.63094534408394366E-002],]
