# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          55 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncldy_subarea=[[         1],]
input.jclea=[[         1],]
input.jcldy=[[         2],]
input.afracsub=[[  0.99369054655916056E+000,  0.63094534408394366E-002,],]
input.relhumgcm=[[  0.89237549945883410E+000],]
input.maxsubarea=[[         2],]
# Output data is stored here.
output = Object()
output.relhumsub=[[  0.89169213603386299E+000,  0.10000000000000000E+001,],]
