# This file was automatically generated by skywalker.

from math import nan as nan

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'gas_aer_uptkrates_1box1gas'
# Input is stored here.
input = Object()
input.temp = [273, ]
input.aernum = [[2253176149, 2.253176149e+10, 2253176.149, 4506352298, ],]
input.uptkaer = [[2.868401394e-12, 1.626999245e-13, 1.543231389e-10, 4.532199604e-13, ],]
input.lnsg = [[0.5877866649, 0.4700036292, 0.5877866649, 0.4700036292, ],]
input.dgncur_awet = [[1.263835114e-07, 2.975603003e-08, 2.300066843e-06, 5.067706479e-08, ],]

# Output data is stored here.
output = Object()
output.uptkaer = [[2.868401484e-12, 1.626999304e-13, 1.543231411e-10, 4.532199765e-13, ],]
