# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.dt = [0, ]
input.alogsig = [[0.5877866649, 0.4700036292, 0.5877866649, 0.4700036441, ],]
input.aten = [[1.206437615e-09, ],]
input.cpair = [[1004.64, ],]
input.exp45logsig = [[4.733757267, 2.702197556, 4.733757267, 2.702197727, ],]
input.gravit = [[9.80616, ],]
input.hygro = [[0.398014273, 0.4457640263, 1.109245004, 1.049749674e-07, ],]
input.latvap = [[2501000, ],]
input.na = [[148527899, 2170494082, 80275.85049, 66687660.11, ],]
input.nmode = [[4, ],]
input.pi = [[3.141592654, ],]
input.rair = [[287.0423114, ],]
input.rh2o = [[461.5046398, ],]
input.rhoair = [[1.025062636, ],]
input.rhoh2o = [[1000, ],]
input.sq2 = [[1.414213562, ],]
input.t0 = [[273, ],]
input.tair = [[251.1513232, ],]
input.twothird = [[0.6666666667, ],]
input.volume = [[6.766301198e-13, 7.972117651e-14, 3.473302771e-13, 9.4354201e-14, ],]
input.w_in = [[0.1614331841, ],]
input.wmaxf = [[10, ],]

# Output data is stored here.
output = Object()
output.flux_fullact = [0.1614331841, ]
output.fluxm = [[0.1582100271, 0.01963910815, 0.1614331841, 0, ],]
output.fluxn = [[0.09920235296, 0.0008049828183, 0.1614330282, 0, ],]
output.fm = [[0.980034111, 0.1216547159, 1, 0, ],]
output.fn = [[0.6145102911, 0.004986476744, 0.9999990344, 0, ],]
