# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1417 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.1614331841E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2511513232E+003],]
input.rhoair=[[0.1025062636E+001],]
input.na=[[0.1485278990E+009,0.2170494082E+010,0.8027585049E+005,0.6668766011E+008,],]
input.nmode=[[         4],]
input.volume=[[0.6766301198E-012,0.7972117651E-013,0.3473302771E-012,0.9435420100E-013,],]
input.hygro=[[0.3980142730E+000,0.4457640263E+000,0.1109245004E+001,0.1049749674E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.6145083021E+000,0.4986384050E-002,0.9999990344E+000,0.0000000000E+000,],]
output.fm=[[0.9800338634E+000,0.1216534090E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.9920203185E-001,0.8049678542E-003,0.1614330282E+000,0.0000000000E+000,],]
output.fluxm=[[0.1582099871E+000,0.1963889716E-001,0.1614331841E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.1614331841E+000],]
