# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1400 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2065535991E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2546713763E+003],]
input.rhoair=[[0.1007234792E+001],]
input.na=[[0.8081862344E+008,0.1926580239E+010,0.4463929814E+005,0.6922051814E+008,],]
input.nmode=[[         4],]
input.volume=[[0.3330853319E-012,0.7633532114E-013,0.1810895016E-012,0.9793785943E-013,],]
input.hygro=[[0.4200725253E+000,0.4614486187E+000,0.1124273333E+001,0.1192714206E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.6705987817E+000,0.1137780272E-001,0.9999995406E+000,0.0000000000E+000,],]
output.fm=[[0.9862703974E+000,0.1928334602E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1385145919E+000,0.2350126103E-002,0.2065535042E+000,0.0000000000E+000,],]
output.fluxm=[[0.2037177003E+000,0.3983044523E-001,0.2065535991E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2065535991E+000],]
