# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [ 0.00, ]
input.mam_prevap_resusp_optcc=[ 130]
input.pdel_ik=[ 0.3395589227E+04]
input.evap_ik=[ 0.7626064109E-09]
input.precabx=[ 0.3168724826E-04]
# Output data is stored here.
output = Object()
output.fracevx=[ 0.8333589375E-02]
