# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[         4]
input.pdel=[ 0.3395589227E+04]
input.source_term=[ 0.4201774770E-07]
input.sink_term=[ 0.7626064109E-09]
# Output data is stored here.
output = Object()
output.lprec=[ 0.1428546071E-04]
