# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [ 0.00, ]
input.mam_prevap_resusp_optcc=[ 0]
input.pdel_ik=[ 0.3395589227E+04]
input.omsm=[ 0.1000000000E+01]
input.srcc=[ 0.1164821549E-02]
input.srcs=[ 0.1037333262E-02]
input.srct=[ 0.2202154812E-02]
input.fins=[ 0.0000000000E+00]
input.finc=[ 0.0000000000E+00]
input.fracev_st=[ 0.0000000000E+00]
input.fracev_cu=[ 0.0000000000E+00]
input.resusp_c=[ 0.0000000000E+00]
input.resusp_s=[ 0.0000000000E+00]
input.precs_ik=[ 0.0000000000E+00]
input.evaps_ik=[ 0.7626064109E-09]
input.cmfdqr_ik=[ 0.4201774770E-07]
input.evapc_ik=[ 0.8237076572E-08]
input.scavabs=[ 0.3108640514E+01]
input.scavabc=[ 0.2971030925E+00]
input.precabc=[ 0.3558161196E-04]
input.precabs=[ 0.3168724826E-04]
# Output data is stored here.
output = Object()
output.scavt_ik=[-0.2202154812E-02]
output.iscavt_ik=[ 0.0000000000E+00]
output.icscavt_ik=[ 0.0000000000E+00]
output.isscavt_ik=[ 0.0000000000E+00]
output.bcscavt_ik=[-0.1164821549E-02]
output.bsscavt_ik=[-0.1037333262E-02]
output.rcscavt_ik=[ 0.0000000000E+00]
output.rsscavt_ik=[ 0.0000000000E+00]
output.scavabs=[ 0.3467838983E+01]
output.scavabc=[ 0.7004470625E+00]
output.precabc=[ 0.4727888011E-04]
output.precabs=[ 0.3142317975E-04]
