# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [ 0.00, ]
input.mam_prevap_resusp_optcc=[ 130]
input.is_st_cu=[ 1]
input.precabx_base_old=[ 0.3178588943E-04]
input.precabx_old=[ 0.3168724826E-04]
input.scavabx_old=[ 0.9711083276E-11]
input.precnumx_base_old=[ 0.0000000000E+00]
input.precabx_new=[ 0.3142317975E-04]
# Output data is stored here.
output = Object()
output.scavabx_new=[ 0.9706948328E-11]
output.resusp_x=[ 0.4134947635E-14]
