# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.mam_prevap_resusp_optcc=[ 230]
input.pdel_ik=[ 0.3395589227E+04]
input.omsm=[ 0.1000000000E+01]
input.srcc=[ 0.9919389547E-02]
input.srcs=[ 0.9069025923E-02]
input.srct=[ 0.1898841547E-01]
input.fins=[ 0.0000000000E+00]
input.finc=[ 0.0000000000E+00]
input.fracev_st=[ 0.8333589375E-02]
input.fracev_cu=[ 0.8016109779E-01]
input.resusp_c=[ 0.1272242588E+01]
input.resusp_s=[ 0.9306173331E+01]
input.precs_ik=[ 0.0000000000E+00]
input.evaps_ik=[ 0.7626064109E-09]
input.cmfdqr_ik=[ 0.4201774770E-07]
input.evapc_ik=[ 0.8237076572E-08]
input.scavabs=[ 0.0000000000E+00]
input.scavabc=[ 0.0000000000E+00]
input.precabc=[ 0.4727888011E-04]
input.precabs=[ 0.3142317975E-04]
# Output data is stored here.
output = Object()
output.scavt_ik=[ 0.1156110984E-01]
output.iscavt_ik=[ 0.0000000000E+00]
output.icscavt_ik=[ 0.0000000000E+00]
output.isscavt_ik=[ 0.0000000000E+00]
output.bcscavt_ik=[-0.9919389547E-02]
output.bsscavt_ik=[-0.9069025923E-02]
output.rcscavt_ik=[ 0.3674123558E-02]
output.rsscavt_ik=[ 0.2687540175E-01]
output.scavabs=[ 0.0000000000E+00]
output.scavabc=[ 0.0000000000E+00]
output.precabc=[ 0.4727888011E-04]
output.precabs=[ 0.3142317975E-04]
