# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.is_st_cu=[         1]
input.mam_prevap_resusp_optcc=[       230]
input.pdel_ik=[ 0.3395589227E+04]
input.evapx=[ 0.7626064109E-09]
input.precabx_base_old=[ 0.3178588943E-04]
input.precabx_old=[ 0.3168724826E-04]
input.scavabx_old=[ 0.0000000000E+00]
input.precnumx_base_old=[ 0.3293520152E+03]
# Output data is stored here.
output = Object()
output.precabx_base_new=[ 0.3178588943E-04]
output.precabx_new=[ 0.3142317975E-04]
output.scavabx_new=[ 0.0000000000E+00]
output.precnumx_base_new=[ 0.3293520152E+03]
output.resusp_x=[ 0.9306173331E+01]
