# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          48 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [ 0.00, ]
input.is_st_cu=[ 1]
input.is_strat_cloudborne=[ 1]
input.deltat=[ 0.3600000000E+04]
input.fracp=[ 0.1014289501E-01]
input.precabx=[ 0.3161419202E-04]
input.cldv_ik=[ 0.3628401926E+00]
input.scavcoef_ik=[ 0.0000000000E+00]
input.sol_factb=[ 0.0000000000E+00]
input.sol_facti=[ 0.6000000000E+00]
input.tracer_1=[ 0.4930584477E-09]
input.tracer_2=[ 0.4930584477E-09]
# Output data is stored here.
output = Object()
output.src=[ 0.8335066780E-15]
output.fin=[ 0.1000000000E+01]
