# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.accom=[[  0.65000000000000002E+000],]
input.gasdiffus=[[  0.98927952023118366E-005],]
input.gasfreepath=[[  0.14477505834902675E-006],]
input.beta_inp=[[  0.00000000000000000E+000],]
input.n_mode=[[         4],]
input.dgncur_awet=[[  0.18398320084554579E-006,  0.41852164809827782E-007,  0.22709324611755489E-005,  0.10000008207619799E-006,],]
input.lnsg=[[  0.58778666490211906E+000,  0.47000362924573563E+000,  0.58778666490211906E+000,  0.47000364414689666E+000,],]
# Output data is stored here.
output = Object()
output.uptkrate=[[  0.47561227380588870E-011,  0.26847542945697144E-012,  0.14556295690265713E-009,  0.13852616601675826E-011,],]
