# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.deltat = [30, ]
input.do_bc = [1, ]
input.do_dst1 = [1, ]
input.do_dst3 = [1, ]
input.eswtr = [1e-06, ]
input.r_bc = [6.7e-08, ]
input.r_dust_a1 = [2.58e-07, ]
input.r_dust_a3 = [1.576e-06, ]
input.rgdep = [1e-08, ]
input.sigma_iv = [0.0235, ]
input.temperature = [253.15, ]
input.vwice = [3.251768272e-29, ]
input.uncoated_aer_num = [[1000, 1000, 1000, ],]

# Output data is stored here.
output = Object()
output.frzbcdep = [0.3333333333, ]
output.frzdudep = [2.082018261e-08, ]
