# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.bcmac = [1e-05, 1e-05, ]
input.bcmc = [7e-05, 7e-05, ]
input.bcmpc = [3e-05, 3e-05, ]
input.dmac = [2e-05, 2e-05, ]
input.dmc = [0, 4e-05, ]
input.mommc = [6e-05, 6e-05, ]
input.ncoarse = [1000000, 1000000, ]
input.pommc = [8e-06, 8e-06, ]
input.soamc = [9e-06, 9e-06, ]
input.ssmc = [5e-05, 5e-05, ]
input.total_interstitial_aer_num = [[0, 0, 0, ],[0, 0, 0, ],]

# Output data is stored here.
output = Object()
output.total_interstitial_aer_num = [[18676608, 69680, 0, ],[18676608, 69680, 0.1687763713, ],]
