# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.bcmac = [3e-06, ]
input.bcmc = [8e-06, ]
input.mommac = [4e-06, ]
input.mommc = [7e-06, ]
input.num_accum = [1000000, ]
input.num_coarse = [1000000, ]
input.pommac = [5e-06, ]
input.pommc = [9e-06, ]
input.so4mac = [1e-06, ]
input.so4mc = [6e-06, ]
input.soamac = [2e-06, ]
input.soamc = [1e-07, ]
input.awcam = [[0, 0, 0, ],]
input.awfacm = [[0, 0, 0, ],]
input.total_interstitial_aer_num = [[100000, 200000, 300000, ],]

# Output data is stored here.
output = Object()
output.awcam = [[1500000000, 3000000000, 9030000000, ],]
output.awfacm = [[0.9333333333, 0.9333333333, 0.8006644518, ],]
