# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.bcmac = [1e-06, ]
input.bcmpc = [2e-06, ]
input.dmac = [3e-06, ]
input.dmc = [4e-06, ]
input.hetraer = [[0, 0, 0, ],]
input.total_interstitial_aer_num = [[100000, 200000, 300000, ],]

# Output data is stored here.
output = Object()
output.hetraer = [[1.615081991e-07, 1.112610363e-07, 1.069774545e-07, ],]
