# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.aw = [1.1, ]
input.rgimm = [1e-05, ]
input.sigma_iw = [0.75, ]
input.supersatice = [1.2, ]
input.temperature = [253.15, ]
input.vwice = [1e-05, ]

# Output data is stored here.
output = Object()
output.do_spec_flag = [1, ]
output.rgimm = [1.546554152e+16, ]
