# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.bcmac_cb = [0, 0, 0, 0, 4e-05, 4e-05, 4e-05, 4e-05, ]
input.bcmc_cb = [9.75e-05, 9.75e-05, 9.75e-05, 9.75e-05, 9.75e-05, 9.75e-05, 9.75e-05, 9.75e-05, ]
input.dmac_cb = [0, 1e-05, 0, 1e-05, 0, 1e-05, 0, 1e-05, ]
input.dmc_cb = [0, 0, 8e-05, 8e-05, 0, 0, 8e-05, 8e-05, ]
input.mommac_cb = [7e-05, 7e-05, 7e-05, 7e-05, 7e-05, 7e-05, 7e-05, 7e-05, ]
input.mommc_cb = [9.5e-05, 9.5e-05, 9.5e-05, 9.5e-05, 9.5e-05, 9.5e-05, 9.5e-05, 9.5e-05, ]
input.num_accum_cb = [1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, ]
input.num_coarse_cb = [2000000, 2000000, 2000000, 2000000, 2000000, 2000000, 2000000, 2000000, ]
input.pommac_cb = [5e-05, 5e-05, 5e-05, 5e-05, 5e-05, 5e-05, 5e-05, 5e-05, ]
input.pommc_cb = [8.5e-05, 8.5e-05, 8.5e-05, 8.5e-05, 8.5e-05, 8.5e-05, 8.5e-05, 8.5e-05, ]
input.so4mac_cb = [3e-05, 3e-05, 3e-05, 3e-05, 3e-05, 3e-05, 3e-05, 3e-05, ]
input.soamac_cb = [6e-05, 6e-05, 6e-05, 6e-05, 6e-05, 6e-05, 6e-05, 6e-05, ]
input.soamc_cb = [7.75e-05, 7.75e-05, 7.75e-05, 7.75e-05, 7.75e-05, 7.75e-05, 7.75e-05, 7.75e-05, ]
input.ssmac_cb = [2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, ]
input.ssmc_cb = [9e-05, 9e-05, 9e-05, 9e-05, 9e-05, 9e-05, 9e-05, 9e-05, ]
input.total_cloudborne_aer_num = [[0, 0, 0, ],[0, 0, 0, ],[0, 0, 0, ],[0, 0, 0, ],[0, 0, 0, ],[0, 0, 0, ],[0, 0, 0, ],[0, 0, 0, ],]

# Output data is stored here.
output = Object()
output.total_cloudborne_aer_num = [[0, 0, 0, ],[0, 0.04166666667, 0, ],[0, 0, 0.3047619048, ],[0, 0.04166666667, 0.3047619048, ],[0.1481481481, 0, 0, ],[0.1428571429, 0.03571428571, 0, ],[0.1481481481, 0, 0.3047619048, ],[0.1428571429, 0.03571428571, 0.3047619048, ],]
