# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.Kcoll_bc = [1e-12, ]
input.Kcoll_dust_a1 = [1e-12, ]
input.Kcoll_dust_a3 = [1e-12, ]
input.deltat = [30, ]
input.do_bc = [1, ]
input.do_dst1 = [1, ]
input.do_dst3 = [1, ]
input.eswtr = [1e-06, ]
input.icnlx = [100000, ]
input.r_bc = [6.7e-08, ]
input.r_dust_a1 = [2.58e-07, ]
input.r_dust_a3 = [1.576e-06, ]
input.rgimm = [1e-08, ]
input.sigma_iv = [0.0235, ]
input.temperature = [253.15, ]
input.uncoated_aer_num = [[1000, 1000, 1000, ],]

# Output data is stored here.
output = Object()
output.frzbccnt = [0.1294171699, ]
output.frzducnt = [6.661338148e-14, ]
