# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.r3lx = [1e-06, ]
input.aw = [[1, 1, 1, ],]
input.awcam = [[100, 200, 300, ],]
input.awfacm = [[100, 200, 300, ],]
input.total_interstitial_aer_num = [[1000, 2000, 3000, ],]

# Output data is stored here.
output = Object()
output.aw = [[1.011020986, 1.021677613, 1.031818311, ],]
