# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.rgimm = [0.0001, ]
input.sigma_iw = [0.001, ]

# Output data is stored here.
output = Object()
output.dg0imm = [4.188790205e-11, ]
