# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.dg0imm = [2, ]
input.rgimm = [0.0001, ]
input.temperature = [263.15, ]
input.vwice = [1e-50, ]

# Output data is stored here.
output = Object()
output.Aimm = [12561.12076, ]
