# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.deltat = [600, ]
input.dt = [0, ]
input.icnlx = [722.8291816, ]
input.pressure = [64338.48985, ]
input.r3lx = [4e-06, ]
input.supersatice = [11.04098322, ]
input.temperature = [258.033745, ]
input.awcam = [[0.2307553765, 0.0001969930059, 0.002437033755, ],]
input.awfacm = [[0.4587007863, 0.4587007863, 0.4884884581, ],]
input.coated_aer_num = [[17.38866107, 0.01484448451, 0.003842325245, ],]
input.dstcoat = [[1, 1, 1, ],]
input.fn = [[0, 0, 0, ],]
input.hetraer = [[6.700000252e-08, 2.975911183e-07, 7.80719106e-07, ],]
input.total_aer_num = [[17.38866107, 0.01484448451, 0.003842325245, ],]
input.total_cloudborne_aer_num = [[17.38866107, 0.01484448451, 0.003842325245, ],]
input.total_interstitial_aer_num = [[17.38866107, 0.01484448451, 0.003842325245, ],]
input.uncoated_aer_num = [[17.38866107, 0.01484448451, 0.003842325245, ],]

# Output data is stored here.
output = Object()
output.frzbccnt = [0.0002898110178, ]
output.frzbcdep = [0.0002898110178, ]
output.frzbcimm = [0.0002898110178, ]
output.frzducnt = [8.115253596e-06, ]
output.frzdudep = [3.114468292e-05, ]
output.frzduimm = [3.114468292e-05, ]
