# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          54 , time step=        1111 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.nmodes=[[         4],]
input.dest_mode_of_mode=[[         0,         1,         0,         0,         0,],]
# Output data is stored here.
output = Object()
output.num_pairs=[[         1],]
output.sz_factor=[[ 0.2478589509E+01, 0.1414867332E+01, 0.0000000000E+00, 0.0000000000E+00,],]
output.fmode_dist_tail_fac=[[ 0.0000000000E+00, 0.1504470870E+01, 0.0000000000E+00, 0.0000000000E+00,],]
output.v2n_lo_rlx=[[ 0.0000000000E+00, 0.2897945990E+26, 0.0000000000E+00, 0.0000000000E+00,],]
output.v2n_hi_rlx=[[ 0.0000000000E+00, 0.1861703373E+21, 0.0000000000E+00, 0.0000000000E+00,],]
output.ln_diameter_tail_fac=[[ 0.0000000000E+00, 0.6627102345E+00, 0.0000000000E+00, 0.0000000000E+00,],]
output.diameter_cutoff=[[ 0.0000000000E+00, 0.8178434821E-07, 0.0000000000E+00, 0.0000000000E+00,],]
output.ln_dia_cutoff=[[ 0.0000000000E+00,-0.1631917995E+02, 0.0000000000E+00, 0.0000000000E+00,],]
output.diameter_threshold=[[ 0.0000000000E+00, 0.8096650551E-07, 0.0000000000E+00, 0.0000000000E+00,],]
