# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.so4vol=[[  0.78776908479016344E+006],]
input.newnuc_method_flagaa=[[        11],]
input.newnuc_method_flagaa2=[[         2],]
input.ratenucl=[[  0.12690084802925376E-071],]
input.rateloge=[[ -0.16554789082420373E+003],]
input.cnum_tot=[[  0.12603486825834364E+004],]
input.cnum_h2so4=[[  0.14414987162270899E+003],]
input.cnum_nh3=[[  0.00000000000000000E+000],]
input.radius_cluster=[[  0.21928326134908684E+001],]
# Output data is stored here.
output = Object()
output.newnuc_method_flagaa2=[[        11],]
output.ratenucl=[[  0.78776908479016339E+000],]
output.rateloge=[[ -0.23855027167514486E+000],]
output.cnum_tot=[[  0.57923915977259153E+001],]
output.cnum_h2so4=[[  0.57923915977259153E+001],]
output.cnum_nh3=[[  0.00000000000000000E+000],]
output.radius_cluster=[[  0.50000000000000000E+000],]
