# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.temp=[[  0.29775449169937525E+003],]
input.rh=[[  0.81985597081405814E+000],]
input.so4vol=[[  0.78776908479016344E+006],]
# Output data is stored here.
output = Object()
output.ratenucl=[[  0.12690084802925376E-071],]
output.rateloge=[[ -0.16554789082420373E+003],]
output.cnum_h2so4=[[  0.14414987162270899E+003],]
output.cnum_tot=[[  0.12603486825834364E+004],]
output.radius_cluster=[[  0.21928326134908684E+001],]
