# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dtnuc=[[  0.36000000000000000E+004],]
input.temp_in=[[  0.29775449169937525E+003],]
input.rh_in=[[  0.81985597081405814E+000],]
input.press_in=[[  0.97834305473446453E+005],]
input.zm_in=[[  0.28891463999989116E+003],]
input.pblh_in=[[  0.79393332557991255E+003],]
input.qh2so4_cur=[[  0.33545008036974121E-013],]
input.qh2so4_avg=[[  0.33101653321820026E-013],]
input.qnh3_cur=[[  0.00000000000000000E+000],]
input.h2so4_uptkrate=[[  0.14451280301338871E-002],]
input.mw_so4a_host=[[  0.11500000000000000E+003],]
input.newnuc_method_flagaa=[[        11],]
input.nsize=[[         1],]
input.maxd_asize=[[         1],]
input.dplom_sect=[[  0.12485878488089052E-007,],]
input.dphim_sect=[[  0.52000000000000002E-007,],]
input.ldiagaa=[[        -1],]
input.rgas=[[  0.83144675910000014E+001],]
input.avogad=[[  0.60221399999999997E+024],]
input.mw_so4a=[[  0.96000000000000000E+002],]
input.mw_nh4a=[[  0.18000000000000000E+002],]
# Output data is stored here.
output = Object()
output.isize_nuc=[[         1],]
output.qnuma_del=[[  0.20911781900832846E-002],]
output.qso4a_del=[[  0.39296060039942731E-022],]
output.qnh4a_del=[[  0.00000000000000000E+000],]
output.qh2so4_del=[[ -0.39296060039942731E-022],]
output.dens_nh4so4a=[[  0.17700000000000000E+004],]
output.dnclusterdt=[[  0.78776908479016344E+006],]
