# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          47 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.modal_aerosols=[[         1],]
input.rah2o2=[[ 0.2299048586E+06],]
input.h2o2g=[[ 0.1950914917E-09],]
input.so2g=[[ 0.1398888325E-10],]
input.o3g=[[ 0.3525157484E-07],]
input.rao3=[[ 0.2293484540E+07],]
input.patm=[[ 0.5212504349E+00],]
input.dtime=[[ 0.3600000000E+04],]
input.t_factor=[[ 0.3415485654E-03],]
input.xlwc=[[ 0.2045167481E-07],]
input.const0=[[ 0.1660302175E-20],]
input.xhnm=[[ 0.1414006739E+20],]
input.heo3=[[ 0.2756953511E-01],]
input.heso2=[[ 0.4232233599E+04],]
input.xso2=[[ 0.1401575499E-10],]
input.xso4=[[ 0.2538078474E-10],]
input.xso4_init=[[ 0.0000000000E+00],]
input.xh2o2=[[ 0.2579731039E-09],]
# Output data is stored here.
output = Object()
output.xso2=[[ 0.1254780676E-10],]
output.xso4=[[ 0.2684873296E-10],]
output.xso4_init=[[ 0.2673628746E-10],]
output.xh2o2=[[ 0.2566176012E-09],]
output.xdelso4hp_ik=[[ 0.1355502721E-11],]
