# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          37 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.modal_aerosols=[[         1],]
input.rah2o2=[[ 0.1619963824E+05],]
input.h2o2g=[[ 0.1449458958E-11],]
input.so2g=[[ 0.8288438427E-11],]
input.o3g=[[ 0.3320974478E-07],]
input.rao3=[[ 0.7604852026E+07],]
input.patm=[[ 0.2330199987E+00],]
input.dtime=[[ 0.3600000000E+04],]
input.t_factor=[[ 0.1068378555E-02],]
input.xlwc=[[ 0.3811135505E-07],]
input.const0=[[ 0.1660302175E-20],]
input.xhnm=[[ 0.7563840017E+19],]
input.heo3=[[ 0.1772207508E+00],]
input.heso2=[[ 0.1394691906E+07],]
input.xso2=[[ 0.1645944394E-10],]
input.xso4=[[ 0.7008637581E-14],]
input.xso4_init=[[ 0.7152100476E-03],]
input.xh2o2=[[ 0.9095418644E-10],]
# Output data is stored here.
output = Object()
output.xso2=[[ 0.1000000000E-19],]
output.xso4=[[ 0.1646645258E-10],]
output.xso4_init=[[ 0.3547609758E-12],]
output.xh2o2=[[ 0.9060643410E-10],]
output.xdelso4hp_ik=[[ 0.3477523382E-12],]
