# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          47 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.yph=[[ 0.4500000000E+01],]
input.fact1_so2=[[ 0.9053783481E-12],]
input.fact2_so2=[[ 0.1620489001E-05],]
input.fact3_so2=[[ 0.3471076418E-01],]
input.fact4_so2=[[ 0.8795971763E-07],]
input.Eco2=[[ 0.3840367910E-11],]
input.Eh2o=[[ 0.1000000000E-13],]
input.Eso4=[[ 0.2913498396E-04],]
input.so4_fact=[[ 0.1000000000E+01],]
# Output data is stored here.
output = Object()
output.xph=[[ 0.3162277660E-04],]
output.ynetpos=[[ 0.2337294773E-05],]
