# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          47 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.temperature=[[ 0.2704710575E+03],]
input.patm=[[ 0.5212504349E+00],]
input.xlwc=[[ 0.2045167481E-07],]
input.t_factor=[[ 0.3415485654E-03],]
input.xso2=[[ 0.1401575499E-10],]
input.xso4=[[ 0.2538078474E-10],]
input.xhnm=[[ 0.1414006739E+20],]
input.so4_fact=[[ 0.1000000000E+01],]
input.Ra=[[ 0.8205280039E-01],]
input.xkw=[[ 0.1000000000E-13],]
input.const0=[[ 0.1660302175E-20],]
# Output data is stored here.
output = Object()
output.converged=[[         1],]
output.xph=[[ 0.2939420500E-04],]
