# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.scath2o=[[  0.82311147606397293E-012],]
input.absh2o=[[ -0.10111904763559041E-020],]
input.sumhygro=[[  0.27168163535835007E-012],]
input.sumscat=[[  0.28110435855827377E-011],]
input.sumabs=[[ -0.12412054510810687E-013],]
input.hygro_s=[[  0.55924622541961198E-016],]
input.palb=[[  0.95001719732746914E+000],]
input.dopaer=[[  0.30605624267874931E-002],]
input.scat_s=[[  0.12829766347861686E-014],]
input.abs_s=[[ -0.16008897501676748E-017],]
input.aod_s=[[  0.40147139978248075E-004],]
# Output data is stored here.
output = Object()
output.scat_s=[[  0.51668034688335271E-003],]
output.abs_s=[[  0.12897864385972587E-003],]
output.aod_s=[[  0.41669163577420384E-004],]
