# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=           0 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.ncoef=[[         5],]
input.coef=[[  0.10900927581965057E+002, -0.27866016477117478E+000, -0.95264002849610707E+000, -0.50121062362733115E+000,  0.20039082901914285E+000,],]
input.cheb_k=[[  0.10000000000000000E+001, -0.57184921844850656E+000, -0.34597694271966450E+000,  0.96754250703939437E+000, -0.76059991021270823E+000,],]
# Output data is stored here.
output = Object()
output.para=[[  0.53020470430925375E+001],]
