# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.specmmr_k=[[  0.45244286569388789E-009],]
input.mass_k=[[  0.34389585824000443E+003],]
input.vol=[[  0.25561743824513439E-012],]
input.specrefr=[[  0.14303349523758979E+001],]
input.specrefi=[[  0.99999999392252903E-008],]
input.hygro_aer=[[  0.50700000000000001E+000],]
# Output data is stored here.
output = Object()
output.burden_s=[[  0.15559322760236662E-006],]
output.scat_s=[[  0.36561855635880332E-012],]
output.abs_s=[[ -0.25561743669162683E-020],]
output.hygro_s=[[  0.12959804119028314E-012],]
