# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.p3=[[ 0.3523139380E-02],]
input.p2=[[ 0.0000000000E+00],]
input.p1=[[-0.2230816457E-02],]
input.p0=[[-0.4915397298E-05],]
# Output data is stored here.
output = Object()
output.real_cx=[[-0.2203413642E-02, -0.6577608061E-01,  0.1302324355E+00, -0.6577608061E-01, ],]
output.imag_cx=[[ 0.0000000000E+00,  0.1131501554E+00,  0.2775557562E-16, -0.1131501554E+00, ],]
