# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.rdry_in=[[ 0.1117402402E-06],]
input.hygro=[[ 0.2052752129E+00],]
input.rh=[[ 0.7098335324E+00],]
# Output data is stored here.
output = Object()
output.rwet_out=[[ 0.1302324355E-06],]
