# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.rhcrystal=[[ 0.3500000000E+00, 0.3500000000E+00, 0.3500000000E+00, 0.3500000000E+00,],]
input.rhdeliques=[[ 0.8000000000E+00, 0.8000000000E+00, 0.8000000000E+00, 0.8000000000E+00,],]
input.dgncur_a=[[ 0.1330978176E-06, 0.4132278142E-07, 0.1394631584E-05, 0.1000000012E-06,],]
input.dryrad=[[ 0.1117402402E-06, 0.2877830753E-07, 0.1170841648E-05, 0.6964271883E-07,],]
input.hygro=[[ 0.2052752129E+00, 0.1944073080E+00, 0.5890183536E+00, 0.6149771289E-07,],]
input.rh=[[ 0.7098335324E+00],]
input.naer=[[ 0.2264456039E+09, 0.5281324971E+09, 0.2867674196E+05, 0.1665751220E+07,],]
input.dryvol=[[ 0.5844096935E-20, 0.9983535284E-22, 0.6723309375E-17, 0.1414867471E-20,],]
# Output data is stored here.
output = Object()
output.wetrad=[[ 0.1269461515E-06, 0.3226945269E-07, 0.1561329156E-05, 0.6964272200E-07,],]
output.wetvol=[[ 0.8569337107E-20, 0.1407548629E-21, 0.1594307241E-16, 0.1414867664E-20,],]
output.wtrvol=[[ 0.2725240171E-20, 0.4091951007E-22, 0.9219763040E-17, 0.1932349114E-27,],]
output.dgncur_awet=[[ 0.1512101254E-06, 0.4633571792E-07, 0.1859755295E-05, 0.1000000057E-06,],]
output.qaerwat=[[ 0.6171186563E-09, 0.2161092303E-10, 0.2643927656E-09, 0.3218812893E-18,],]