# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temperature=[[ 0.2804261386E+03],]
input.pmid=[[ 0.6753476429E+05],]
input.h2ommr=[[ 0.6818013995E-02],]
input.cldn=[[ 0.4131862680E-01],]
# Output data is stored here.
output = Object()
output.rh=[[ 0.7098335324E+00],]
