# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.wetvol=[[ 0.8569337107E-20, 0.1407548629E-21, 0.1594307241E-16, 0.1414867664E-20,],]
input.wtrvol=[[ 0.2725240171E-20, 0.4091951007E-22, 0.9219763040E-17, 0.1932349114E-27,],]
input.drymass=[[ 0.6775249809E-17, 0.1112290319E-18, 0.1010841977E-13, 0.1533519601E-17,],]
input.specdens_1=[[ 0.1770000000E+04, 0.1770000000E+04, 0.2600000000E+04, 0.1000000000E+04,],]
input.wetdens=[[ 0.1108479733E+04, 0.1081583671E+04, 0.1212553267E+04, 0.1084622866E+04,],]
# Output data is stored here.
output = Object()
output.wetdens=[[ 0.1108661016E+04, 0.1080946966E+04, 0.1212324846E+04, 0.1083860938E+04,],]
