# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          54 , time step=        1416 ]
# This file was generated by E3SM.

from math import nan as nan, inf as inf


# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass


# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [
    0.00,
]
input.lamda = [
    [0.8712940717e-07],
]
input.kfmat = [
    [0.3256635422e-11],
]
input.kfmac = [
    [0.3210390006e-11],
]
input.kfmatac = [
    [0.3233264697e-11],
]
input.knc = [
    [0.1471191895e-15],
]
input.dgatk = [
    [0.7185055288e-07],
]
input.dgacc = [
    [0.2076746571e-06],
]
input.sgatk = [
    [0.1600000000e01],
]
input.sgacc = [
    [0.1800000000e01],
]
input.xxlsgat = [
    [0.4700036292e00],
]
input.xxlsgac = [
    [0.5877866649e00],
]
# Output data is stored here.
output = Object()
output.qn11 = [
    [0.1103438439e-14],
]
output.qn22 = [
    [0.8079794552e-15],
]
output.qn12 = [
    [0.3537489739e-14],
]
output.qv12 = [
    [0.1780772039e-35],
]
