# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          54 , time step=        1416 ]
# This file was generated by E3SM.

from math import nan as nan, inf as inf


# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass


# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [
    0.00,
]
input.deltat = [
    [0.3600000000e04],
]
input.ybetaij0 = [
    [
        0.1138913853e-15,
        0.7643285106e-16,
        0.7164149793e-16,
    ],
]
input.ybetaii0 = [
    [
        0.3552579420e-16,
        0.3095670504e-16,
        0.3552579420e-16,
    ],
]
input.ybetajj0 = [
    [
        0.2601333325e-16,
        0.2601333325e-16,
        0.3095670504e-16,
    ],
]
input.qnum_bgn = [
    [
        0.2785493168e11,
        0.2653541833e10,
        0.3842768383e07,
        0.6597712901e10,
        0.0000000000e00,
    ],
]
input.qnum_end = [
    [
        0.2785493168e11,
        0.2653541833e10,
        0.3842768383e07,
        0.6597712901e10,
        0.0000000000e00,
    ],
]
# Output data is stored here.
output = Object()
output.qnum_end = [
    [
        0.2778245950e11,
        0.2618123311e10,
        0.3842768383e07,
        0.6542610949e10,
        0.0000000000e00,
    ],
]
output.qnum_tavg = [
    [
        0.2781869559e11,
        0.2635832572e10,
        0.0000000000e00,
        0.6570161925e10,
        0.0000000000e00,
    ],
]
