# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          54 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.deltat=[[ 0.3600000000E+04],]
input.ybetaij0=[[ 0.1138913853E-15, 0.7643285106E-16, 0.7164149793E-16,],]
input.ybetaii0=[[ 0.3552579420E-16, 0.3095670504E-16, 0.3552579420E-16,],]
input.ybetajj0=[[ 0.2601333325E-16, 0.2601333325E-16, 0.3095670504E-16,],]
input.qnum_bgn=[[ 0.2785493168E+11, 0.2653541833E+10, 0.3842768383E+07, 0.6597712901E+10, 0.0000000000E+00,],]
input.qnum_end=[[ 0.2785493168E+11, 0.2653541833E+10, 0.3842768383E+07, 0.6597712901E+10, 0.0000000000E+00,],]
# Output data is stored here.
output = Object()
output.qnum_end=[[ 0.2778245950E+11, 0.2618123311E+10, 0.3842768383E+07, 0.6542610949E+10, 0.0000000000E+00,],]
output.qnum_tavg=[[ 0.2781869559E+11, 0.2635832572E+10, 0.0000000000E+00, 0.6570161925E+10, 0.0000000000E+00,],]
