# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          70 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.lchnk=[[       137],]
input.delta_t=[[  0.36000000000000000E+004],]
input.pdel=[[  0.81892176620561804E+003],]
input.o3l_vmr=[[  0.55938203020011289E-007],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.mwdry=[[  0.28966000000000001E+002],]
input.mwo3=[[  0.48000000000000000E+002],]
input.rgrav=[[  0.10197671667604852E+000],]
input.do_lin_strat_chem=[[         1],]
input.o3_tau=[[  0.17280000000000000E+006],]
input.o3_lbl=[[         4],]
input.o3_sfc=[[  0.29999999999999997E-007],]
# Output data is stored here.
output = Object()
output.o3l_vmr=[[  0.55403413853551216E-007],]
