# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'get_relaxed_v2n_limits'
# Input is stored here.
input = Object()
input.v2nmin = [1, ]
input.do_aitacc_transfer = [0, ]
input.v2nmax = [1, ]
input.is_aitken_mode = [0, ]
input.is_accum_mode = [0, ]

# Output data is stored here.
output = Object()
output.v2nmin = [1, ]
output.v2nmax = [1, ]
output.v2nminrl = [0.03703703704, ]
output.v2nmaxrl = [27, ]
