# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'aitken_accum_exchange'
# Input is stored here.
input = Object()
input.dt = [3600.00, ]
input.max_k = [0, ]
input.interstitial = [[ 0.7299469308E-09, 0.1811687805E-08, 0.2991980389E-08, 0.1911597588E-09, 0.1123090476E-09, 0.7563458575E-11, 0.1356030726E-11, 0.2715374903E-11, 0.1327543704E-10, 0.1034802167E-16, 0.9187966638E-17, 0.3683174593E-09, 0.2421325192E-10, 0.1126298407E-10, 0.2008344526E-11, 0.1872262953E-10, 0.3028730249E-10, 0.4394763138E-13, 0.1065451952E-08, 0.1107541088E-09, 0.1828532564E-16, ],]
input.interstitial_num = [[ 0.6298684716E+09, 0.4787904689E+08, 0.6472553148E+05, 0.7326120905E+09, ],]
input.cloud_borne = [[ 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, ],]
input.cloud_borne_num = [[ 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, ],]

input.v2nnom_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]
input.v2nmin_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]
input.v2nmax_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]

input.dgnnom_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]
input.dgnmin_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]
input.dgnmax_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]

input.common_factor_nmodes = [[1.0, 1.0, 1.0, 1.0, ],]

input.num_i_k_aitsv = [1.0, ]
input.num_c_k_aitsv = [1.0, ]
input.num_i_k_accsv = [1.0, ]
input.num_c_k_accsv = [1.0, ]

input.dryvol_i_aitsv = [1.0, ]
input.dryvol_c_aitsv = [1.0, ]
input.dryvol_i_accsv = [1.0, ]
input.dryvol_c_accsv = [1.0, ]

input.dgncur_i_k = [1.0, ]
input.dgncur_c_k = [1.0, ]

input.v2ncur_c_k = [1.0, ]
input.v2ncur_i_k = [1.0, ]

# Output data is stored here.
output = Object()
output.cloud_borne_ptend = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],]
output.cloud_borne_ptend_num = [[0, 0, 0, 0, ],]
output.interstitial_ptend = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],]
output.interstitial_ptend_num = [[0, 0, 0, 0, ],]
