# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'compute_tendencies'
# Input is stored here.
input = Object()
input.dt = [0, ]
input.t = [0, ]
input.cloud_borne_num = [[0, 0, 0, 0, ],]
input.interstitial_num = [[809835459.7, 44254275.27, 140084.0545, 1382391601, ],]
input.cloud_borne = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],]
input.interstitial = [[1.218350564e-09, 3.560443333e-09, 4.203338951e-09, 3.723412167e-10, 2.330196615e-10, 1.435909119e-11, 2.704344376e-12, 2.116400132e-12, 1.326256343e-11, 1.741610336e-17, 1.280539377e-17, 1.045693148e-09, 5.35872285e-11, 2.926142847e-11, 3.986256848e-12, 3.751267639e-11, 0.04679337373, 9.456518445e-14, 2.272248527e-09, 2.351792086e-10, 2.733926271e-17, ],]

# Output data is stored here.
output = Object()
output.interstitial_ptend_num = [[0, 0, 0, 0, ],]
output.cloud_borne_ptend_num = [[0, 0, 0, 0, ],]
output.interstitial_ptend = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],]
output.cloud_borne_ptend = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],]
