# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'adjust_num_sizes'
# Input is stored here.
input = Object()
input.v2nminrl = [1, ]
input.drv_c = [1, ]
input.v2nmax = [1, ]
input.init_num_i = [1, ]
input.v2nmaxrl = [1, ]
input.dt = [1, ]
input.drv_i = [1, ]
input.dqdt = [1, ]
input.v2nmin = [1, ]
input.init_num_c = [1, ]
input.dqqcwdt = [1, ]

# Output data is stored here.
output = Object()
output.dqdt = [0, ]
output.dqqcwdt = [0, ]
