# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'compute_dry_volume'
# Input is stored here.
input = Object()
input.interstitial = [[1.218350564e-09, 3.560443333e-09, 4.203338951e-09, 3.723412167e-10, 2.330196615e-10, 1.435909119e-11, 2.704344376e-12, 2.116400132e-12, 1.326256343e-11, 1.741610336e-17, 1.280539377e-17, 1.045693148e-09, 5.35872285e-11, 2.926142847e-11, 3.986256848e-12, 3.751267639e-11, 0.04679337373, 9.456518445e-14, 2.272248527e-09, 2.351792086e-10, 2.733926271e-17, ],]
input.cloud_borne = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],]

# Output data is stored here.
output = Object()
output.dryvol_c = [[0, 0, 0, 0, ],]
output.dryvol_i = [[8.770009704e-12, 1.445828688e-14, 4.679337422e-05, 2.410589255e-12, ],]
