# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'get_relaxed_v2n_limits'
# Input is stored here.
input = Object()
input.do_aitacc_transfer = [0, ]

# Output data is stored here.
output = Object()
output.v2nmaxrl = [[7.113737097e+22, 2.89794599e+25, 1.089329229e+19, 1.908306128e+25, ],]
output.v2nminrl = [[1.754177754e+17, 1.861703373e+20, 2.334810591e+14, 2.617703879e+19, ],]
output.v2nmin = [[4.736279937e+18, 5.026599108e+21, 6.303988596e+15, 7.067800474e+20, ],]
output.v2nmax = [[2.634717443e+21, 1.07331333e+24, 4.034552701e+17, 7.067800474e+23, ],]
