# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Settings are stored here.
settings = Object()
settings.function = 'adjust_num_sizes'
# Input is stored here.
input = Object()
input.dt = [1, ]
input.v2nmaxrl = [[7.113737097e+28, 2.89794599e+25, 1.089329229e+19, 1.908306128e+25, ],]
input.interstitial_num = [[809835459.7, 44254275.27, 140084.0545, 1382391601, ],]
input.v2nminrl = [[1.754177754e+17, 1.861703373e+14, 2.334810591e+14, 2.617703879e+19, ],]
input.dryvol_c = [[0, 0, 0, 0, ],]
input.cloud_borne_num = [[0, 0, 0, 0, ],]
input.v2nmax = [[2.634717443e+27, 1.07331333e+24, 4.034552701e+17, 7.067800474e+23, ],]
input.dryvol_i = [[8.770009704e-12, 1.445828688e-14, 4.679337422e-05, 2.410589255e-12, ],]
input.v2nmin = [[4.736279937e+18, 5.026599108e+15, 6.303988596e+15, 7.067800474e+20, ],]

# Output data is stored here.
output = Object()
output.interstitial_tend = [[0, 0, 3414175.432, 3719.499849, ],]
output.cloudborne_tend = [[0, 0, 0, 0, ],]
output.num_i = [[809835459.7, 44254275.27, 3554259.487, 1382395320, ],]
output.num_c = [[0, 0, 0, 0, ],]
