# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25132448065995982E+003],]
input.invariants=[[  0.21287907044506137E+020,  0.16817446565159848E+020,  0.44704604793462886E+019,  0.30195331333669776E+017,  0.89633500023180619E+006,  0.60338235285535358E+008,  0.84131872113582030E+008,  0.11712566664683718E+013,],]
input.mtot=[[  0.21287907044506137E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15343142501393238E-011, -0.98765432000000000E+008,  0.37836752320571907E-011, -0.98765432000000000E+008,  0.15042691833808192E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49082057873189930E-011,  0.15343142501393238E-011,  0.99535363274843492E-012,  0.37836752320571907E-011,  0.11824098391007976E-010,  0.15042691833808192E-011,],]
