# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1400 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2094011845E+020,0.1654269358E+020,0.4397424875E+019,0.4018888826E+017,0.8706654328E+006,0.5852783930E+008,0.8204468844E+008,0.1151649027E+013,],]
input.mtot=[[0.2094011845E+020],]
input.rate=[[-.9876543200E+008,0.4874449546E-011,0.1547236166E-011,0.9808320566E-012,0.3830369767E-011,0.1132613951E-010,0.1463821484E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1566922028E-014,0.1347125046E-005,0.8539765671E-006,0.3334970551E-005,0.9861278159E-005,0.8567430861E-004,],]
