# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          54 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.airtemp=[[ 0.2785271976E+03],]
input.airprs=[[ 0.7455859940E+05],]
input.dgatk=[[ 0.7185055288E-07],]
input.dgacc=[[ 0.2076746571E-06],]
input.sgatk=[[ 0.1600000000E+01],]
input.sgacc=[[ 0.1800000000E+01],]
input.xxlsgat=[[ 0.4700036292E+00],]
input.xxlsgac=[[ 0.5877866649E+00],]
input.pdensat=[[ 0.1087762736E+04],]
input.pdensac=[[ 0.1119326722E+04],]
# Output data is stored here.
output = Object()
output.betaij0=[[ 0.3537489739E-14],]
output.betaii0=[[ 0.1103438439E-14],]
output.betajj0=[[ 0.8079794552E-15],]
output.betaij3=[[ 0.1776645941E-14],]
