# Data at [lat=   71.9201421331276      , lon=   71.5690366721838      , k=          64 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.Temperature=[[-0.3269480152E+02],]
input.w_vlc=[[ 0.2000000000E+00],]
input.Ns=[[ 0.9478315467E-03],]
# Output data is stored here.
output = Object()
output.Nis=[[ 0.9478315467E-03],]
output.Nid=[[ 0.0000000000E+00],]
