# Data at [lat=   71.9201421331276      , lon=   71.5690366721838      , k=          64 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.Temperature=[[-0.3769480152E+02],]
input.w_vlc=[[ 0.2000000000E+00],]
input.RH=[[ 0.8382408292E+00],]
input.Na=[[ 0.6224210438E+02],]
# Output data is stored here.
output = Object()
output.Ni=[[ 0.3021368690E+00],]
