# Data at [lat=   71.9201421331276      , lon=   71.5690366721838      , k=          64 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.modeptr_accum=[[         1],]
input.modeptr_aitken=[[         2],]
input.modeptr_coarse=[[         3],]
input.numptr_amode=[[        23,        28,        36,        40,],]
input.alnsg_amode=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.lptr_dust_a_amode=[[        20,-999888777,        29,-999888777,],]
input.lptr_nacl_a_amode=[[        21,        26,        30,-999888777,],]
input.lptr_so4_a_amode=[[        16,        24,        31,-999888777,],]
input.lptr_bc_a_amode=[[        19,-999888777,        32,        38,],]
input.lptr_pom_a_amode=[[        17,-999888777,        33,        37,],]
input.lptr_soa_a_amode=[[        18,        25,        34,-999888777,],]
input.lptr_mom_a_amode=[[        22,        27,        35,        39,],]
input.ncol=[[         4],]
input.lchnk=[[       136],]
input.temperature=[[ 0.2378457014E+03],]
input.state_q=[[ 0.1691718148E-03, 0.0000000000E+00, 0.4443171907E-06, 0.1172034280E+08, 0.3270620347E+04, 0.8316984984E-09, 0.6631901851E-06, 0.2480873558E+01, 0.1687830519E+03, 0.6904267833E-07, 0.3300307612E-11, 0.1125502939E-10, 0.7739043283E-09, 0.5014807362E-13, 0.2245458505E-09, 0.8980692555E-09, 0.2152539857E-10, 0.3673798005E-09, 0.2560705195E-10, 0.1555588133E-11, 0.2678551644E-11, 0.2149558887E-12, 0.2620464307E+09, 0.3400487059E-10, 0.3202989633E-10, 0.5554260656E-15, 0.1497506340E-16, 0.3434235658E+09, 0.1807667558E-10, 0.1477547096E-09, 0.1442160446E-11, 0.3471642529E-13, 0.1280343677E-12, 0.2151641601E-11, 0.1392372471E-13, 0.6474282102E+04, 0.1406416528E-10, 0.4860795442E-10, 0.3498445013E-17, 0.2661475205E+08,],]
input.pmid=[[ 0.9377624033E+05],]
input.rho=[[ 0.1373572514E+01],]
input.wsubi=[[ 0.2000000000E+00],]
input.ast=[[ 0.9990000000E+00],]
input.dgnum=[[ 0.1117680669E-06, 0.4731958792E-07, 0.1752052657E-05, 0.1000000012E-06,],]
# Output data is stored here.
output = Object()
output.naai=[[ 0.1397785118E+05],]
output.naai_hom=[[ 0.2199642654E+06],]
