# This file was automatically generated by skywalker.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass

# Input is stored here.
input = Object()
input.air_density = [1.3, ]
input.cloud_fraction = [0.01, ]
input.dry_diameter_aitken = [5.2e-08, ]
input.dst3_num = [1e-07, ]
input.pressure = [100000, ]
input.relative_humidity = [0.001, ]
input.so4_num = [1e-08, ]
input.subgrid_in = [4000, ]
input.temperature = [230, ]
input.updraft_vel_ice_nucleation = [0.01, ]

# Output data is stored here.
output = Object()
output.nuci = [0.07692307692, ]
output.onidep = [0, ]
output.onihf = [0, ]
output.oniimm = [0.07692307692, ]
output.onimey = [0, ]
