# Data at [lat=   71.9201421331276      , lon=   71.5690366721838      , k=          64 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.wbar=[[ 0.2000000000E+00],]
input.tair=[[ 0.2378457014E+03],]
input.pmid=[[ 0.9377624033E+05],]
input.relhum=[[ 0.8382408292E+00],]
input.cldn=[[ 0.9990000000E+00],]
input.rhoair=[[ 0.1373572514E+01],]
input.so4_num=[[ 0.6224210438E+02],]
input.dst3_num=[[ 0.9478315467E-03],]
input.subgrid=[[ 0.1200000000E+01],]
# Output data is stored here.
output = Object()
output.nuci=[[ 0.1397785118E+05],]
output.onihf=[[ 0.2199642654E+06],]
output.oniimm=[[ 0.6900484228E+03],]
output.onidep=[[ 0.0000000000E+00],]
output.onimey=[[ 0.0000000000E+00],]
