# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72464334858145390E+005],]
input.pmk=[[  0.24469107414180282E+002],]
input.pmid1d_up=[[  0.71159910352611172E+005],]
input.pmid1d_down=[[  0.73785749968427845E+005],]
input.temp1d_up=[[  0.24961247644450839E+003],]
input.temp1d_down=[[  0.25157915543785055E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.73990524736880434E-002],]
output.tm=[[  0.25059581594117947E+003],]
