# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1417 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72573764634530744E+005],]
input.pmk=[[  0.24479659314842522E+002],]
input.pmid1d_up=[[  0.71266714478333088E+005],]
input.pmid1d_down=[[  0.73897848253595628E+005],]
input.temp1d_up=[[  0.24874724170831706E+003],]
input.temp1d_down=[[  0.25116092138846039E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.90994776166355811E-002],]
output.tm=[[  0.24995408154838873E+003],]
