# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1411 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72492384254482531E+005],]
input.pmk=[[  0.24471813195912915E+002],]
input.pmid1d_up=[[  0.71187286733223111E+005],]
input.pmid1d_down=[[  0.73814483365194654E+005],]
input.temp1d_up=[[  0.24989035144233088E+003],]
input.temp1d_down=[[  0.25169871960941350E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.67971823466329261E-002],]
output.tm=[[  0.25079453552587219E+003],]
