# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72467086531935580E+005],]
input.pmk=[[  0.24469372887161839E+002],]
input.pmid1d_up=[[  0.71162596002874314E+005],]
input.pmid1d_down=[[  0.73788568743330252E+005],]
input.temp1d_up=[[  0.24976256133062128E+003],]
input.temp1d_down=[[  0.25166057965921004E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.71373491505774692E-002],]
output.tm=[[  0.25071157049491566E+003],]
