# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72332857500513521E+005],]
input.pmk=[[  0.24456414485033196E+002],]
input.pmid1d_up=[[  0.71031587659435987E+005],]
input.pmid1d_down=[[  0.73651066464810152E+005],]
input.temp1d_up=[[  0.25115610335309742E+003],]
input.temp1d_down=[[  0.25344591960440539E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.85617530283671455E-002],]
output.tm=[[  0.25230101147875141E+003],]
