# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1407 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72495152890752724E+005],]
input.pmk=[[  0.24472080231534235E+002],]
input.pmid1d_up=[[  0.71189988938996932E+005],]
input.pmid1d_down=[[  0.73817319516245640E+005],]
input.temp1d_up=[[  0.25008288588395445E+003],]
input.temp1d_down=[[  0.25221102938751423E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.79878071283044361E-002],]
output.tm=[[  0.25114695763573431E+003],]
