# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72514680100586964E+005],]
input.pmk=[[  0.24473963428688194E+002],]
input.pmid1d_up=[[  0.71209047614179770E+005],]
input.pmid1d_down=[[  0.73837322908353613E+005],]
input.temp1d_up=[[  0.25002583181366370E+003],]
input.temp1d_down=[[  0.25169061370797536E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.62552463593941393E-002],]
output.tm=[[  0.25085822276081953E+003],]
