# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1414 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pm=[[  0.72468323373376799E+005],]
input.pmk=[[  0.24469492211455311E+002],]
input.pmid1d_up=[[  0.71163803167603095E+005],]
input.pmid1d_down=[[  0.73789835745846271E+005],]
input.temp1d_up=[[  0.24936608287253554E+003],]
input.temp1d_down=[[  0.25151401152975339E+003],]
input.cnst_kap=[[  0.28571658640413355E+000],]
input.cnst_faktor=[[ -0.34162768385490476E-001],]
# Output data is stored here.
output = Object()
output.dtdz=[[ -0.80858281976216948E-002],]
output.tm=[[  0.25044004720114447E+003],]
